### ISSUE TITLE
bug submitting new bmark via api

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#183]
Traceback (most recent call last):
  File "/home/bmark.us/0.5/lib/python2.6/site-packages/pyramid/router.py", line 187, in **call**
    response = self.handle_request(request)
  File "/home/bmark.us/0.5/lib/python2.6/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/bmark.us/0.5/lib/python2.6/site-packages/pyramid_tm/**init**.py", line 100, in tm_tween
    response = handler(request)
  File "/home/bmark.us/0.5/lib/python2.6/site-packages/pyramid/router.py", line 164, in handle_request
    response = view_callable(context, request)
  File "/home/bmark.us/0.5/lib/python2.6/site-packages/pyramid/config/views.py", line 343, in rendered_view
    result = view(context, request)
  File "/home/bmark.us/0.5/lib/python2.6/site-packages/pyramid/config/views.py", line 474, in _requestonly_view
    response = view(request)
  File "<string>", line 2, in bmark_add
  File "./bookie/lib/access.py", line 270, in wrap_action
    return action_(_args, *_kwargs)
  File "./bookie/views/api.py", line 188, in bmark_add
    mark = _update_mark(mark, params)
  File "./bookie/views/api.py", line 130, in _update_mark
    new_tags = TagMgr.from_string(new_tag_str)
  File "./bookie/models/__init__.py", line 130, in from_string
    tag_list = set([tag.lower().strip() for tag in tag_str.split(" ")])
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by mitechie** [comment]
Fixed in 190c7c36ee4
