### ISSUE TITLE
new error to catch during readable/existing.py

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#34]
http://www.scribd.com/doc/30715288/The-Open-Graph-Protocol-Design-Decisions
Traceback (most recent call last):
  File "scripts/readability/existing.py", line 70, in <module>
    read = ReadUrl.parse(hashed.url)
  File "/home/rharding/src/bookie/Bookie/Bookie/bookie/lib/readable.py", line 142, in parse
    read.set_content(Document(fh.read()).summary())
  File "/usr/lib/python2.6/socket.py", line 329, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.6/httplib.py", line 518, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.6/httplib.py", line 561, in _read_chunked
    raise IncompleteRead(''.join(value))
httplib.IncompleteRead: IncompleteRead(7365 bytes read)

**Comment by mitechie** [comment]
This has been caught now and running a new test against the massive.xml looking for other errors.
