### ISSUE TITLE
Testing error

### ISSUE THREAD

**Issue by dyladan** [bookieio/Bookie#433]
On a fresh git clone following the instructions in the docs to the letter I get the following:

``` bash
$ git clone ....
...
$ make install
...
$ INI=test.ini make test_bookie.db
bin/python bin/alembic -c test_alembic.ini upgrade head
INFO  [alembic.migration] Context impl SQLiteImpl.
INFO  [alembic.migration] Will assume transactional DDL.
$ make test
INI="test.ini" NLTK_DATA="/home/user/bookie/download-cache/nltk" bin/python bin/py.test -q --tb=short -s bookie/tests

USING TEST INI:  test.ini
............/home/user/bookie/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:459: SAWarning: Unicode type received non-unicode bind param value.
  param.append(processors[key](compiled_params[key]))
............................s........................2014-04-22 09:53:36,535 ERROR [bookie.views.auth][MainThread] CHECKING
2014-04-22 09:53:36,536 ERROR [bookie.views.auth][MainThread] testing@gmail.com
2014-04-22 09:53:36,536 ERROR [bookie.views.auth][MainThread] testing@gmail.com
2014-04-22 09:53:36,536 ERROR [bookie.views.auth][MainThread] testing@gmail.com
.........................................................................................
153 passed, 1 skipped in 45.35 seconds
Traceback (most recent call last):
  File "bin/py.test", line 9, in <module>
    load_entry_point('pytest==2.5.2', 'console_scripts', 'py.test')()
  File "/home/user/bookie/local/lib/python2.7/site-packages/_pytest/config.py", line 20, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/user/bookie/local/lib/python2.7/site-packages/_pytest/core.py", line 377, in __call__
    return self._docall(methods, kwargs)
  File "/home/user/bookie/local/lib/python2.7/site-packages/_pytest/core.py", line 388, in _docall
    res = mc.execute()
  File "/home/user/bookie/local/lib/python2.7/site-packages/_pytest/core.py", line 289, in execute
    res = method(**kwargs)
  File "/home/user/bookie/local/lib/python2.7/site-packages/_pytest/main.py", line 112, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/user/bookie/local/lib/python2.7/site-packages/_pytest/main.py", line 107, in wrap_session
    config.do_unconfigure()
  File "/home/user/bookie/local/lib/python2.7/site-packages/_pytest/config.py", line 613, in do_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/home/user/bookie/local/lib/python2.7/site-packages/_pytest/core.py", line 377, in __call__
    return self._docall(methods, kwargs)
  File "/home/user/bookie/local/lib/python2.7/site-packages/_pytest/core.py", line 388, in _docall
    res = mc.execute()
  File "/home/user/bookie/local/lib/python2.7/site-packages/_pytest/core.py", line 289, in execute
    res = method(**kwargs)
  File "/home/user/bookie/local/lib/python2.7/site-packages/_pytest/assertion/__init__.py", line 64, in pytest_unconfigure
    sys.meta_path.remove(hook)
ValueError: list.remove(x): x not in list
make: *** [test] Error 1
```

I'm not sure where this error is coming from but i'm willing to help troubleshoot if anyone has an idea.

**Comment by craigmaloney** [comment]
That's a known issue with Pytest. We ran into it last week, and Rick has
a patch for the CI system. It can be safely ignored.
