### ISSUE TITLE
TypeError: unable to add header to the response in api export

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#522]
https://bookie.io/api/v1/admin/bmarks/export?api_key=xxxxxxx

Traceback (most recent call last):
  File "/home/bmark.us/0.5/Bookie/lib/python2.7/site-packages/raven/middleware.py", line 35, in **call**
    iterable = self.application(environ, start_response)
  File "/home/bmark.us/0.5/Bookie/lib/python2.7/site-packages/pyramid/router.py", line 243, in **call**
    return response(request.environ, start_response)
  File "/home/bmark.us/0.5/Bookie/lib/python2.7/site-packages/webob/response.py", line 1021, in **call**
    start_response(self.status, headerlist)
TypeError: unable to add header to the response

**Comment by AnishShah** [comment]
It is working properly for me. I used Python Requests library to check and the response headers contains CORS headers.
