### ISSUE TITLE
make install fails on Ubuntu 14.04 and Mint 17.1

### ISSUE THREAD

**Issue by nagordon** [bookieio/Bookie#563]
With Ubuntu 14.04 and Mint 17.1 and Anaconda Python 2.7 installed, I receive this error when running 

command

``` bash
make install
```

Error

``` python
Collecting tweepy==2.3.0 (from -r requirements.txt (line 51))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-5IaLOn/tweepy/setup.py", line 4, in <module>
        from tweepy import __version__
      File "tweepy/__init__.py", line 16, in <module>
        from tweepy.auth import OAuthHandler, AppAuthHandler
      File "tweepy/auth.py", line 10, in <module>
        from tweepy import oauth
      File "tweepy/oauth.py", line 30, in <module>
        import hmac
      File "/home/neal/anaconda/lib/python2.7/hmac.py", line 8, in <module>
        from operator import _compare_digest as compare_digest
    ImportError: cannot import name _compare_digest

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5IaLOn/tweepy
make: *** [deps] Error 1
```

**Comment by mitechie** [comment]
A quick search seems to imply that your version of python is slightly out of date. 

http://stackoverflow.com/questions/26535043/python-flask-error-importerror-cannot-import-name-compare-digest

Can you verify your full python 2.7 version and see if there's an update available?

**Comment by craigmaloney** [comment]
Bah, sorry. Thought I was canceling what I was writing. Mea culpa.

**Comment by nagordon** [comment]
``` python
In [3]: print 'Python version ' + sys.version
Python version 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
```

also, after running `conda update --all` all packages are up to date
